print ('Alyannah Marie Rey');
print ('Hupi Santa Cruz Marinduque');
print ('October 10, 2001');
print ('Marinduque State College');
print ('Bachelor of Science in Information Technology');
print ('2-F');
print ('Singing');
print ('Dancing');
print ('Cooking');
print ('Reading');
print ('Swimming');